#!/usr/bin/env python3
"""ledger.py — regenerate LEDGER.md from OBLIGATION/DISCHARGED tags in GSArith/**/*.lean.

Usage:
  ledger.py            rewrite LEDGER.md
  ledger.py --check    exit 1 if LEDGER.md is stale (CI)
  ledger.py --selftest parse test/LedgerTags.lean: expect exactly one valid and one malformed tag

Any malformed tag anywhere in GSArith/ is an error (exit 2).  Grammar: see GSArith/Ledger.lean.
"""
from __future__ import annotations
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "GSArith"
OUT = ROOT / "LEDGER.md"

TRIGGER = re.compile(r"--\s*(OBLIGATION|DISCHARGED)\[")
GRAMMAR = re.compile(
    r"^\s*--\s*(?P<status>OBLIGATION|DISCHARGED)"
    r"\[(?P<source>stacks:[0-9A-Z]{4}(?:,[0-9A-Z]{4})*|lit:[^\]\s]+|paper:[^\]\s]+)\]"
    r"\[tier:(?P<tier>[ABC])\]"
    r"\[crit:(?P<crit>yes|no)\]"
    r"\[prop:(?P<prop>[^\]\s]+)\]"
    r"\s+(?P<desc>\S.*?)\s*$"
)

def scan(paths):
    """Return (entries, errors).  entries: list of dicts; errors: list of 'file:line: msg'."""
    entries, errors = [], []
    for path in paths:
        depth = 0  # block-comment nesting; tags inside `/- … -/` (docstrings) are not scanned
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            in_block = depth > 0
            depth += line.count("/-") - line.count("-/")
            if in_block or not TRIGGER.search(line):
                continue
            m = GRAMMAR.match(line)
            rel = path.relative_to(ROOT).as_posix()
            if not m:
                errors.append(f"{rel}:{lineno}: malformed obligation tag: {line.strip()}")
                continue
            d = m.groupdict()
            d.update(file=rel, line=lineno)
            entries.append(d)
    return entries, errors

def render(entries):
    open_ = [e for e in entries if e["status"] == "OBLIGATION"]
    done = [e for e in entries if e["status"] == "DISCHARGED"]
    def count(es, key, val): return sum(1 for e in es if e[key] == val)
    lines = ["# Obligations ledger", "",
             "Generated by `scripts/ledger.py` from `OBLIGATION`/`DISCHARGED` tags in `GSArith/`. "
             "Do not edit by hand.", "",
             f"**Open obligations: {len(open_)}** "
             f"(tier A: {count(open_,'tier','A')}, B: {count(open_,'tier','B')}, C: {count(open_,'tier','C')}; "
             f"on the critical path: {count(open_,'crit','yes')}).  "
             f"Discharged: {len(done)}.", ""]
    for title, es in (("Open", open_), ("Discharged", done)):
        lines += [f"## {title}", ""]
        if not es:
            lines += ["_none_", ""]; continue
        lines += ["| Paper | Source | Tier | Crit | Location | Statement |", "|---|---|---|---|---|---|"]
        for e in sorted(es, key=lambda e: (e["file"], e["line"])):
            lines.append(f"| {e['prop']} | `{e['source']}` | {e['tier']} | {e['crit']} | "
                         f"`{e['file']}:{e['line']}` | {e['desc']} |")
        lines.append("")
    return "\n".join(lines)

def main(argv):
    if "--selftest" in argv:
        entries, errors = scan([ROOT / "test" / "LedgerTags.lean"])
        ok = len(entries) == 1 and len(errors) == 1 and entries[0]["status"] == "OBLIGATION"
        print(("PASS" if ok else "FAIL") + f": selftest parsed {len(entries)} valid, {len(errors)} malformed")
        for err in errors: print("  (expected) " + err)
        return 0 if ok else 1
    entries, errors = scan(sorted(SRC.rglob("*.lean")))
    if errors:
        for err in errors: print(err, file=sys.stderr)
        return 2
    text = render(entries)
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("LEDGER.md is stale; run scripts/ledger.py", file=sys.stderr)
            return 1
        print(f"LEDGER.md up to date ({len(entries)} tag(s)).")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} tag(s))")
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
